.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "BOOSTER" "1" "January 2021" ""
.SH "NAME"
\fBbooster\fR \- fast and secure initramfs generator
.SH "DESCRIPTION"
\fBBooster\fR is a tool to create initramfs images used at the early stage of Linux boot process\. Booster is made with speed and full disk encryption use\-case in mind\.
.P
Booster advantages:
.IP "\[ci]" 4
Fast image build time and fast boot time\.
.IP "\[ci]" 4
Out\-of\-box support for LUKS\-based full disk encryption setup\.
.IP "\[ci]" 4
Clevis style data binding\. The encrypted filesystem can be bound to TPM2 chip or to a network service\. This helps to unlock the drive automatically but only if the TPM2/network service presents\.
.IP "\[ci]" 4
Easy to configure\.
.IP "\[ci]" 4
Automatic host configuration discovery\. This helps to create minimalistic images specific for the current host\.
.IP "" 0
.SH "CONFIG FILE"
\fBbooster\fR generator config file is located at \fB/etc/booster\.yaml\fR\. Here is a sample config file:
.IP "" 4
.nf
network:
  dhcp: on
  ip: 10\.0\.2\.15/24
  gateway: 10\.0\.2\.255
  dns_servers: 192\.168\.1\.1,8\.8\.8\.8
universal: false
modules: nvidia,kernel/sound/usb/
compression: zstd
mount_timeout: 5m6s
extra_files: vim,/usr/share/vim/vim82/
.fi
.IP "" 0
.IP "\[ci]" 4
\fBnetwork\fR node, if presents, initializes network at the boot time\. It is needed if mounting a root fs requires access to the network (e\.g\. in case of Tang binding)\. The network can be either configured dynamically with DHCPv4 or statically within this config\. In the former case \fBdhcp\fR is set to \fBon\fR\. In the latter case the config allows to specify \fBip\fR \- the machine IP address and its network mask, \fBgateway\fR \- default gateway, \fBdns_servers\fR \- comma\-separated list of DNS servers\.
.IP "\[ci]" 4
\fBuniversal\fR is a boolean flag that tells booster to generate a universal image\. By default booster generates a host\-specific image that includes kernel modules used at the current host\. For example if the host does not have a TPM2 chip then tpm modules are ignored\. Universal image includes many kernel modules and tools that might be needed at a broad range of hardware configurations\.
.IP "\[ci]" 4
\fBmodules\fR is a comma\-separates list of extra modules to add to the generated image\. One can use a module name or a path relative to the modules dir (/usr/lib/modules/$KERNEL_VERSION)\. If the path ends with slash symbol (/) then it considered a directory and all modules from this directory needs to be added recursively\. booster also takes modules dependencies into account, all dependencies of the specified modules will be added to the image as well\.
.IP "\[ci]" 4
\fBcompression\fR is a flag that specifies compression for the output initramfs file\. Currently supported algorithms are "zstd", "gzip", "none"\. If no option specified then "zstd" is used as a default compression\.
.IP "\[ci]" 4
\fBmount_timeout\fR timeout for waiting for root filesystem to appear\. The field format is a decimal number and then unit number\. Valid units are "s", "m", "h"\. If no value specified then default timeout (3 minutes) is used\. To disable the timeout completely specify "0s"\.
.IP "\[ci]" 4
\fBextra_files\fR is a comma\-separated list of extra files to add to the image\. If an item starts with slash ("/") then it considered an absolute path\. Otherwise it is a path relative to /usr/bin\. If the item is a directory then its content is added recursively\. A special case is \fBbusybox\fR, adding it to the image enables emergency shell in case of a panic during the boot process\.
.IP "" 0
.SH "OPTIONS"
\fBbooster\fR command accepts following arguments:
.IP "\[ci]" 4
\fB\-universal\fR generate a universal image
.IP "\[ci]" 4
\fB\-kernelVersion\fR use modules for the given kernel version\. If the flag is not specified then the current kernel is used (as reported by "uname \-r")\.
.IP "\[ci]" 4
\fB\-output\fR output file, by default booster\.img used
.IP "\[ci]" 4
\fB\-compression\fR output file compression\. Currently supported compression algorithms are "zstd" (default) and "gzip"\.
.IP "\[ci]" 4
\fB\-force\fR overwrite output file if it exists
.IP "" 0
.SH "BOOT TIME KERNEL PARAMETERS"
Some parts of booster boot functionality can be modified with kernel boot parameters\. These parameters are usually set through bootloader config\. Booster boot uses following kernel parameters:
.IP "\[ci]" 4
\fBroot=($PATH|UUID=$UUID|LABEL=$LABEL)\fR root device\. It can be specified as a path to the block device (e\.g\. root=/dev/sda) or with filesystem UUID (e\.g\. root=UUID=fd59d06d\-ffa8\-473b\-94f0\-6584cb2b6665, pay atenntion that it does not contain any quotes) or with filesystem label (e\.g\. root=LABEL=rootlabel, pay attention that label does not contain any quotes or whitespaces)\.
.IP "\[ci]" 4
\fBrootfstype=$TYPE\fR (e\.g\. rootfstype=ext4)\. By default booster tries to detect the root filesystem type\. But if the autodetection does not work then this kernel parameter is useful\. Also please file a ticket so we can improve the code that detects filetypes\.
.IP "\[ci]" 4
\fBrootflags=$OPTIONS\fR mount options for the root filesystem, e\.g\. rootflags=user_xattr,nobarrier\.
.IP "\[ci]" 4
\fBrd\.luks\.uuid=$UUID\fR UUID of the LUKS partition where the root partition is enclosed\. booster will try to unlock this LUKS device\.
.IP "\[ci]" 4
\fBrd\.luks\.name=$UUID=$NAME\fR similar to rd\.luks\.uuid parameter but also specifies the name used for the LUKS device opening\.
.IP "\[ci]" 4
\fBrd\.luks\.options=opt1,opt2\fR a comma\-separated lists of LUKS flags\. Supported options are \fBdiscard\fR, \fBsame\-cpu\-crypt\fR, \fBsubmit\-from\-crypt\-cpus\fR, \fBno\-read\-workqueue\fR, \fBno\-write\-workqueue\fR\. Note that booster also supports LUKS v2 persistent flags stored with the partition metadata\. Any command\-line options are added on top of the persistent flags\.
.IP "\[ci]" 4
\fBbooster\.debug=1\fR enable booster debug output\. It is printed to console at the boot time\. This feature might be useful to debug booster issues\.
.IP "" 0
.SH "EXAMPLES"
Create an initramfs file specific for the current kernel/host\. The output file is booster\.img:
.IP "" 4
.nf
$ booster
.fi
.IP "" 0
.P
The same as above but output image to /tmp/foobar\.img:
.IP "" 4
.nf
$ booster /tmp/foobar\.img
.fi
.IP "" 0
.P
Create an universal image with many modules (such as SATA/TPM/NVME/\|\.\|\.\|\. drivers) included:
.IP "" 4
.nf
$ booster \-universal
.fi
.IP "" 0
.P
Create an initramfs for kernel version 5\.4\.91\-1\-lts and copy it to /boot/booster\-lts\.img:
.IP "" 4
.nf
$ booster \-kernelVersion 5\.4\.91\-1\-lts \-output /boot/booster\-lts\.img
.fi
.IP "" 0
.P
Here is a \fBsystemd\-boot\fR configuration stored at /boot/loader/entries/booster\.conf\. In this example e122d09e\-87a9\-4b35\-83f7\-2592ef40cefa is a UUID for the LUKS partition and 08684949\-bcbb\-47bb\-1c17\-089aaa59e17e is a UUID for the encrypted filesystem (e\.g\. ext4)\. Please refer for your bootloader documentation for more info about its configuration\.
.IP "" 4
.nf
title Linux with Booster
linux /vmlinuz\-linux
initrd /booster\-linux\.img
options rd\.luks\.uuid=e122d09e\-87a9\-4b35\-83f7\-2592ef40cefa root=UUID=08684949\-bcbb\-47bb\-1c17\-089aaa59e17e rw
.fi
.IP "" 0
.SH "COPYRIGHT"
Booster is Copyright (C) 2020 Anatol Pomazau \fIhttp://github\.com/anatol\fR
.SH "SEE ALSO"
Project homepage \fIhttps://github\.com/anatol/booster\fR
