version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      anatol-libs:
        patterns:
          - "github.com/anatol/*"
    open-pull-requests-limit: 10
